### PR TITLE
Feature/morestatus

### PR DESCRIPTION
**Pull request by RoyWilliams**
Lasair has a system status https://lasair-iris.roe.ac.uk/status/. I have modified it so that it keeps data about not only today, but past days also.

### CODE REVIEW

**Comment by gpfrancis** [comment]
1. Why does `__main__` in `manage_status.py` contain what appears to be a copy of the test? Not necessarily a problem, but if there's a good reason for it then it should be documented.
2. Can we add XML test output for the benefit of Jenkins? This requires adding the following to `__main__` in the test:
```
    import xmlrunner
    runner = xmlrunner.XMLTestRunner(output='test-reports')
    unittest.main(testRunner=runner)
```
See `watchlist_test.py` for an example.

**Comment by gpfrancis** [comment]
The test result now shows up in Jenkins - but it's labeled as TestAnnotations. Is this correct? If not, then the name of the class should be changed (`manage_status_test.py` on line 7).

**Comment by RoyWilliams** [comment]
Fixed

**Comment by gpfrancis** [comment]
Looks good to me. Happy for @genghisken to go ahead and merge if he agrees.

**Comment by genghisken** [comment]
I'm going to do the merge, but can I get a quick walk-through of the code on Monday?  I have a whole bunch of questions.  Not least, why are we writing a status file rather than updating a (very simple) database table.  (Databases do all that tedious locking stuff.  I suppose the database could be offline..?)  Does the contents of the status file conform to requirements by monitoring tools? If not should we redesign?

**Comment by RoyWilliams** [comment]
Good questions Ken!

First response is that the status file is a key-value dict, and we don't know what the keys are yet. So its not simple if its a relational table. I suppose we could do it with Cassandra, is that right?

In fact the whole reason for the upgrade comes because I want to add some status data -- how many TNS objects, and how many annotations, and it is really easy to do that with a json file.

But perhaps the deeper question is how to align my simple json system with grafana. Thats where we are supposed to be monitoring, right?
Roy

---
Royal Observatory Edinburgh
***@***.***
07542 869986
________________________________

**Pull request merged**
